### ISSUE TITLE
reuse

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH-SDH/clariah-sdh.github.io#14]
term is unclear, please elaborate

**Comment by AshkanA** [comment]
issue not clear to me

**Comment by rlzijdeman** [comment]
Hi please replace 

"... REUSE. Moreover, ..." 

with

"... REUSE. By reusing vocabularies similar data items will be described in the same vocabularies, making it easier to find and link data. Moreover, ..."

**Comment by AshkanA** [comment]
fixed
