### ISSUE TITLE
remove duplicate entry of 'ty' to previous member

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH-SDH/clariah-sdh.github.io#9]
onder tutorials en outreach pagina's heb je nu 2x in de footer "We owe much to our mythic legends now roaming other lands of data: Rinke Hoekstra, Kathrin Dentler, Francesca Ceolan, and Dimitris Alivanistos " staan, ziet er beetje dubbelop uit

**Comment by AshkanA** [comment]
voor lunch al verbeterd
